(base) PS D:\Fuentes\Bnamericas\covid19_ultrasound\pocovidnet>  python scripts/train_covid19.py --data_dir ../data/cross_validation/ --fold 4 --epochs 30 -m data/30-epocas-filtro
2021-03-28 22:37:26.633463: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Model parameters: {'data_dir': '../data/cross_validation/', 'model_dir': 'data/30-epocas-filtro', 'fold': 4, 'learning_rate': 0.0001, 'epochs': 30, 'batch_size': 16, 'trainable_base_layers': 1, 'img_width': 224, 'img_height': 224, 'model_id': 'vgg_base', 'log_softmax': False, 'model_name': 'test', 'hidden_size': 64}
Loading images...
selected fold: 4

Number of training samples: 1587
Number of testing samples: 562
Class mappings are: ['covid' 'pneumonia' 'regular']
2021-03-28 22:37:35.927675: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-28 22:37:35.928553: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-03-28 22:37:36.920863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 computeCapability: 6.1
coreClock: 1.493GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 104.43GiB/s
2021-03-28 22:37:36.921060: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-28 22:37:36.931439: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-28 22:37:36.931564: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-28 22:37:36.935308: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-03-28 22:37:36.936640: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-03-28 22:37:36.941381: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-03-28 22:37:36.944439: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-03-28 22:37:36.945741: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-28 22:37:36.945952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-03-28 22:37:36.946425: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-28 22:37:36.947047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1050 computeCapability: 6.1
coreClock: 1.493GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 104.43GiB/s
2021-03-28 22:37:36.947258: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-28 22:37:36.947716: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-28 22:37:36.947804: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-28 22:37:36.948301: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-03-28 22:37:36.948775: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-03-28 22:37:36.949469: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-03-28 22:37:36.949890: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-03-28 22:37:36.950409: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-28 22:37:36.950587: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-03-28 22:37:37.492608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-28 22:37:37.492799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2021-03-28 22:37:37.494268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2021-03-28 22:37:37.499848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2987 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-03-28 22:37:37.501180: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Compiling model...
Model has 14747971 parameters
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 224, 224, 3)]     0
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168
_________________________________________________________________
block3_conv2 (Conv2D)        (None, 56, 56, 256)       590080
_________________________________________________________________
block3_conv3 (Conv2D)        (None, 56, 56, 256)       590080
_________________________________________________________________
block3_pool (MaxPooling2D)   (None, 28, 28, 256)       0
_________________________________________________________________
block4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160
_________________________________________________________________
block4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808
_________________________________________________________________
block4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808
_________________________________________________________________
block4_pool (MaxPooling2D)   (None, 14, 14, 512)       0
_________________________________________________________________
block5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808
_________________________________________________________________
block5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808
_________________________________________________________________
block5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808
_________________________________________________________________
block5_pool (MaxPooling2D)   (None, 7, 7, 512)         0
_________________________________________________________________
average_pooling2d (AveragePo (None, 1, 1, 512)         0
_________________________________________________________________
flatten (Flatten)            (None, 512)               0
_________________________________________________________________
dense (Dense)                (None, 64)                32832
_________________________________________________________________
batch_normalization (BatchNo (None, 64)                256
_________________________________________________________________
re_lu (ReLU)                 (None, 64)                0
_________________________________________________________________
dropout (Dropout)            (None, 64)                0
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 195
=================================================================
Total params: 14,747,971
Trainable params: 2,392,963
Non-trainable params: 12,355,008
_________________________________________________________________
Model summary None
Starting training model...
d:\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '
2021-03-28 22:37:38.660313: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
Epoch 1/30
2021-03-28 22:37:39.630983: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-28 22:37:39.929783: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-28 22:37:40.076631: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-28 22:37:40.680778: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021-03-28 22:37:40.726504: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021-03-28 22:37:42.054552: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
99/99 [==============================] - ETA: 0s - loss: 1.1646 - accuracy: 0.51332021-03-28 22:38:08.418309: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.57GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
99/99 [==============================] - 44s 354ms/step - loss: 1.1631 - accuracy: 0.5140 - val_loss: 0.7917 - val_accuracy: 0.7509

Epoch 00001: val_accuracy improved from -inf to 0.75089, saving model to data/30-epocas-filtro\test\fold_4\best_weights
2021-03-28 22:38:23.834090: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2021-03-28 22:38:27.575169: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.46GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-03-28 22:38:27.575648: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.04GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-03-28 22:38:27.677819: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.74GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-03-28 22:38:31.168785: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.55GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-03-28 22:38:44.684001: W tensorflow/core/common_runtime/bfc_allocator.cc:248] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.60GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
Balanced accuracy is: {'val_balanced': 0.5421510673234811}
Epoch 2/30
99/99 [==============================] - 16s 164ms/step - loss: 0.7218 - accuracy: 0.7045
Balanced accuracy is: {'val_balanced': 0.6664326765188834}
Epoch 3/30
99/99 [==============================] - 16s 160ms/step - loss: 0.5863 - accuracy: 0.7921
Balanced accuracy is: {'val_balanced': 0.6681034482758621}
Epoch 4/30
99/99 [==============================] - 16s 158ms/step - loss: 0.5149 - accuracy: 0.8144
Balanced accuracy is: {'val_balanced': 0.6920498084291188}
Epoch 5/30
99/99 [==============================] - 16s 162ms/step - loss: 0.4448 - accuracy: 0.8294
Balanced accuracy is: {'val_balanced': 0.7511159003831418}
Epoch 6/30
99/99 [==============================] - 16s 164ms/step - loss: 0.4313 - accuracy: 0.8461
Balanced accuracy is: {'val_balanced': 0.7291666666666666}
Epoch 7/30
99/99 [==============================] - 16s 160ms/step - loss: 0.4073 - accuracy: 0.8514
Balanced accuracy is: {'val_balanced': 0.7604166666666666}
Epoch 8/30
99/99 [==============================] - 17s 166ms/step - loss: 0.3588 - accuracy: 0.8754
Balanced accuracy is: {'val_balanced': 0.7644061302681991}
Epoch 9/30
99/99 [==============================] - 17s 168ms/step - loss: 0.3212 - accuracy: 0.8808
Balanced accuracy is: {'val_balanced': 0.8073515325670497}
Epoch 10/30
99/99 [==============================] - 16s 163ms/step - loss: 0.3482 - accuracy: 0.8863
Balanced accuracy is: {'val_balanced': 0.7486829501915709}
Epoch 11/30
99/99 [==============================] - 16s 164ms/step - loss: 0.2775 - accuracy: 0.9076
Balanced accuracy is: {'val_balanced': 0.7162356321839081}
Epoch 12/30
99/99 [==============================] - 17s 166ms/step - loss: 0.2701 - accuracy: 0.9044
Balanced accuracy is: {'val_balanced': 0.7253352490421455}
Epoch 13/30
99/99 [==============================] - 17s 169ms/step - loss: 0.3000 - accuracy: 0.8933
Balanced accuracy is: {'val_balanced': 0.811661877394636}
Epoch 14/30
99/99 [==============================] - 16s 161ms/step - loss: 0.2925 - accuracy: 0.8981
Balanced accuracy is: {'val_balanced': 0.7939689381499727}
Epoch 15/30
99/99 [==============================] - 16s 157ms/step - loss: 0.2540 - accuracy: 0.9220
Balanced accuracy is: {'val_balanced': 0.7327586206896551}
Epoch 16/30
99/99 [==============================] - 16s 156ms/step - loss: 0.2255 - accuracy: 0.9235
Balanced accuracy is: {'val_balanced': 0.7916666666666666}
Epoch 17/30
99/99 [==============================] - 16s 156ms/step - loss: 0.2271 - accuracy: 0.9244
Balanced accuracy is: {'val_balanced': 0.7863984674329503}
Epoch 18/30
99/99 [==============================] - 16s 158ms/step - loss: 0.2458 - accuracy: 0.9138
Balanced accuracy is: {'val_balanced': 0.810823754789272}
Epoch 19/30
99/99 [==============================] - 16s 158ms/step - loss: 0.2057 - accuracy: 0.9347
Balanced accuracy is: {'val_balanced': 0.8294204980842911}
Epoch 20/30
99/99 [==============================] - 16s 156ms/step - loss: 0.1981 - accuracy: 0.9394
Balanced accuracy is: {'val_balanced': 0.7373084291187739}
Epoch 21/30
99/99 [==============================] - 16s 156ms/step - loss: 0.2141 - accuracy: 0.9215
Balanced accuracy is: {'val_balanced': 0.7425766283524905}
Epoch 22/30
99/99 [==============================] - 16s 156ms/step - loss: 0.2081 - accuracy: 0.9394
Balanced accuracy is: {'val_balanced': 0.7945402298850576}
Epoch 23/30
99/99 [==============================] - 16s 156ms/step - loss: 0.2057 - accuracy: 0.9373
Balanced accuracy is: {'val_balanced': 0.7252155172413793}
Epoch 24/30
99/99 [==============================] - 16s 157ms/step - loss: 0.1553 - accuracy: 0.9495
Balanced accuracy is: {'val_balanced': 0.8261494252873564}
Epoch 25/30
99/99 [==============================] - 16s 156ms/step - loss: 0.1721 - accuracy: 0.9479
Balanced accuracy is: {'val_balanced': 0.813468801313629}
Epoch 26/30
99/99 [==============================] - 16s 157ms/step - loss: 0.2002 - accuracy: 0.9275
Balanced accuracy is: {'val_balanced': 0.7670019157088123}
Epoch 27/30
99/99 [==============================] - 16s 155ms/step - loss: 0.2198 - accuracy: 0.9243
Balanced accuracy is: {'val_balanced': 0.7901265736179529}
Epoch 28/30
99/99 [==============================] - 16s 165ms/step - loss: 0.1527 - accuracy: 0.9515
Balanced accuracy is: {'val_balanced': 0.8469991789819376}
Epoch 29/30
99/99 [==============================] - 16s 157ms/step - loss: 0.1984 - accuracy: 0.9352
Balanced accuracy is: {'val_balanced': 0.6810344827586207}
Epoch 30/30
99/99 [==============================] - 16s 156ms/step - loss: 0.1857 - accuracy: 0.9435
Balanced accuracy is: {'val_balanced': 0.7756554460864805}
Evaluating network...
classification report sklearn:
              precision    recall  f1-score   support

       covid       1.00      0.45      0.62       116
   pneumonia       0.73      0.90      0.80        96
     regular       0.88      0.98      0.93       350

    accuracy                           0.86       562
   macro avg       0.87      0.78      0.78       562
weighted avg       0.88      0.86      0.84       562

confusion matrix:
[[ 52  26  38]
 [  0  86  10]
 [  0   6 344]]
Traceback (most recent call last):
  File "scripts/train_covid19.py", line 257, in <module>
    plt.plot(np.arange(0, N), H.history['val_loss'], label='val_loss')
  File "d:\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2840, in plot
    return gca().plot(
  File "d:\anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 1743, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "d:\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 273, in __call__
    yield from self._plot_args(this, kwargs)
  File "d:\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 399, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (30,) and (1,)
(base) PS D:\Fuentes\Bnamericas\covid19_ultrasound\pocovidnet>